### ISSUE TITLE
Support other node globals

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/js#3]
Now that core modules have landed, we need to inject the other node globals. (eg: `Buffer`, `process`, etc)

**Comment by matthewmueller** [comment]
hacked on this last night via `babel-insert-globals`, no tests or docs yet. planning on opening a PR soon:

```js
let environment_plugin = require('babel-plugin-transform-inline-environment-variables')
let insert_globals = require('babel-insert-globals')

let code = babel.transform(file.contents, {
  plugins: [
    [environment_plugin],
    [insert_globals, { filepath: file.path, root: config.root }]
  ]
})
```

basically handles the only two things that every JS file should be transpiled with: node global and environment variables

**Comment by dominicbarnes** [comment]
My first impression is that babel is too heavy for such a small task, I was hoping to just copy browserify in this last area too.

However, I'm willing to include it now for the sake of unblocking you from using this plugin. Let's make sure to include some tests, so that I get around to swapping this out, we can prevent regressions.

**Comment by matthewmueller** [comment]
Haha good call. Just ran some benchmarks and browserify's pipeline is much faster. I'm not sure why though, I originally wrote this to avoid parsing twice with insert-module-globals and envify.
