### ISSUE TITLE
failing silently and hanging in `function* npm`

### ISSUE THREAD

**Issue by matthewmueller** [makojs/js#6]
I think this is due to changing it to a generator, but i'm not sure where in the stack the errors are being squelched. I think it can be fixed by changing it back to promise-based, but that's not really fixing the root cause. 

Basically if I just run:

```js
function* npm (file) {
  throw new Error('wtf!')
  // ...
}
```

It'll just hang during the dependencies step.

**Comment by dominicbarnes** [comment]
That's super-weird, is that an issue in `ware` or `wrap-fn`?

**Comment by matthewmueller** [comment]
ahhh sorry false alarm, just debugged it, just `emitter.emit('error', err)` halting the node process. gets me every. time.
