### ISSUE TITLE
Better syntax error handling

### ISSUE THREAD

**Issue by matthewmueller** [makojs/js#7]
Right now if `deps(file.contents, 'js')` fails, there's not much information because it doesn't have much information (just the src as a string)

We can provide much more useful information using the `file.path`.

Babel has some nice code here for generating errors that we could pull out or use as inspiration: https://github.com/babel/babel/tree/master/packages/babel-code-frame

**Comment by matthewmueller** [comment]
Super quick version of what I'm thinking:

```js
    var dependencies = []
    try {
      dependencies = deps(file.contents, 'js')
    } catch (e) {
      e.stack = file.path + '\n\n' + e.stack
      throw e
    }

    // traverse dependencies
    return yield Promise.all(dependencies.map(function (dep) {
```

**Comment by dominicbarnes** [comment]
I'm thinking we can drop [syntax-error](https://www.npmjs.com/package/syntax-error) in a `predependencies` hook. (that way we don't need to augment `file-deps` to also check syntax)

**Comment by matthewmueller** [comment]
oh nice, yah that'll work too.

**Comment by dominicbarnes** [comment]
added in 0.6.0
