### ISSUE TITLE
Project root relative requires

### ISSUE THREAD

**Issue by darsain** [makojs/js#72]
To protect against drowning in the see of relative paths such as `require('../../lib/foo')`, and make maintenance easier.

In this project structure:

```
lib/
  foo.js
index.js
package.json
```

With this `package.json`:

```js
{
  "name": "app",
  ...
}
```

Doing:

```js
const foo = require('app/lib/foo');
```

in any project file should correctly require `lib/foo.js`.

The `package.json` should be looked up in mako's `root`.

This extends the node's resolve logic with nonstandard behavior, and should therefore be used only in top level modules, which are not intended to be depended upon. We should also boldly warn against using it anywhere else.

**Comment by dominicbarnes** [comment]
I was experimenting with the `browser` field in the `package.json`, which adds the ability to do some aliasing. However, it only works 1:1, so you can't get exactly what you are looking for here. I'm probably going to implement some form of `require` rewriting or something. Either way, I'll continue working on this.

**Comment by dominicbarnes** [comment]
@darsain I found something that seems to work pretty well, albeit not _perfectly_. If you pass `resolveOptions.paths`, you can accomplish mostly the same thing. The only big difference is that `app/` is no longer a special prefix/alias. This also avoids needing to change the internals of mako-js, since this is kind of custom behavior that I don't think _necessarily_ belongs in core. (although I'm open to making it first-class in the future if there's enough demaind)

```js
mako.use(js({
  resolveOptions: { paths: [ '/path/to/app/root' ] }
}))
```

Then you can do things like:

```js
const lib = require('lib/foo');
```

Do you think that's a fair compromise? Try this out in a real app, let me know whether or not you think that works/scales.

**Comment by dominicbarnes** [comment]
It is worth noting that the `paths` option is only considered after `node_modules`, so if you have any dependencies with the name `lib`, then that `require` may not work. (it's byfar the biggest limitation of this approach)

**Comment by darsain** [comment]
Hm... the `paths` solution is actually even more comfy than keyword :) Tried it, and it works great!

But there are 3 minor issues I see with this:

1. There is a small part of me that doesn't quite like that it breaks the assumption of a word at the beginning of a require call being a module. But, I'm completely willing to ignore this as the comfort of use this brings is awesome :)
2 I'm a bit afraid this might get deprecated. I've read option docs of resolve modules you are using, and one of them notes "**probably don't use this**". I think it's implemented to mirror `NODE_PATH`, which is noted as being a legacy feature, but part of a locked API nonetheless. Still, fear is there :)
3. You need to pass resolve options to each plugin separately :cry:.

And yeah, the collision with `node_modules` might be a problem, but I couldn't come up with a single real world scenario where this would happen, and wouldn't be easy to work around.

You usually use project relative requires for stuff like `lib/*`, `models/*`, `components/*`, and these things don't collide with any packages used in real world. And the fact that these folder names are usually plural even lowers this possibility.

The only thing I could come up with is if you have a file like `./server.js`, but also a `server` module installed, and you do `require('server')`. But that can be fixed just by appending `.js` to the require call (`require('server.js')`), which fixes the issue, and I'd even consider a best practice, since `require('server')` 100% evokes "I need `server` **module**" in me.

All around, there might be collisions, but unlikely ones, since if you are trying to solve a concern **X**, and you install a module **X**, you won't also need a dir **X**, since this concern is already solved by the module, if you get what I mean :)

Disclosure: I'm desperately trying to squash all reasons against it, as I want this to become a thing even more than the keyword solution :) Doing `require('lib/foo')` would be so comfy!

**Comment by dominicbarnes** [comment]
I will add a test-case that uses `resolveOptions.paths` to make sure that if it does get removed upstream, then we will be notified downstream to work on a fix. In the interim, I will close this issue and we can re-open later.

**Comment by darsain** [comment]
Cool, I'll start using it in my next project. And you didn't have to move a finger. Awesome! :)
