### ISSUE TITLE
subentries TODO

### ISSUE THREAD

**Issue by matthewmueller** [makojs/js#8]
Hey! just realized that you added sub-entry support to mako-js. thanks!

I noticed there was a TODO: https://github.com/makojs/js/blob/master/index.js#L208-L210

I had thought about this before, but isn't that not a problem because by the time you get to `post-dependencies`, all the file types should have been updated? example: `post-read` is where I'm changing the type from `.jade` to `.html`

**Comment by dominicbarnes** [comment]
You are absolutely right, so I'll go ahead and remove that comment.

**Comment by dominicbarnes** [comment]
Released with 0.7.2
