### ISSUE TITLE
Figure out how to do hot module reloads

### ISSUE THREAD

**Issue by matthewmueller** [makojs/js#98]
I think there's a few things that really tie people to using webpack. Seems like a big one is HMR. It'd be great to figure out how to support this to demonstrate how flexible this build system is. 

Maybe it doesn't make sense in this repo though, but some way to add the HMR runtime to your JS payload (just like adding the livereload script) and then an example server-side implementation to make it work.

**Comment by matthewmueller** [comment]
It'd be cool if we could find/develop some standalone version of HMR, it seems like it shouldn't need to be tied to webpack.

**Comment by dominicbarnes** [comment]
I haven't been able to find a standalone version of this, and I'm not interested enough in the feature to develop one of my own. (see #18)

**Comment by matthewmueller** [comment]
Ah okay cool. Yah – sound good to wait then.
